version: "3.8"
services: 
  vuepress:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: vuepress1
    volumes:
      - ./docs:/usr/src/app/docs
      - /usr/src/app/docs/node_modules